---
language: node_js
node_js: "lts/*"
dist: xenial

addons:
  firefox: latest
  chrome: stable

cache:
  yarn: true
  directories:
    - node_modules
    - .eslintcache

before_script:
  - yarn lint
script:
  - yarn test
